import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "@/styles/globals.css";
import Providers from "@/components/providers";
import MobileSupportSoon from "@/components/temp/mobile-support-soon";

const fontSans = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} antialiased font-sans`}
        suppressHydrationWarning
      >
        <div className="hidden lg:block">
          <Providers>{children}</Providers>
        </div>
        <div className="block lg:hidden">
          <MobileSupportSoon />
        </div>
      </body>
    </html>
  );
}
